/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;

import DAO.funcionarios_DAO;
import DAO.livros_DAO;
import conexao.Funcionarios;
import conexao.Livros;
import java.sql.ResultSet;
import static conexao.Livros_.nome;
import java.util.Date;

/**
 *
 * @author will
 */
public class frm_livros extends javax.swing.JFrame {

    /**
     * Creates new form frm_livros
     */
    public frm_livros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo_livros = new javax.swing.JLabel();
        lbl_livro = new javax.swing.JLabel();
        txt_livro = new javax.swing.JTextField();
        lbl_autor = new javax.swing.JLabel();
        txt_autor = new javax.swing.JTextField();
        lbl_editora = new javax.swing.JLabel();
        txt_editora = new javax.swing.JTextField();
        lbl_publicacao = new javax.swing.JLabel();
        txt_publicacao = new javax.swing.JTextField();
        lbl_endereco = new javax.swing.JLabel();
        txt_endereco_Livros = new javax.swing.JTextField();
        lbl_genero = new javax.swing.JLabel();
        cb_genero = new javax.swing.JComboBox<>();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_paginas = new javax.swing.JLabel();
        txt_qtdPaginas = new javax.swing.JTextField();
        lbl_classificacao = new javax.swing.JLabel();
        cb_classificacao = new javax.swing.JComboBox<>();
        lbl_danificado = new javax.swing.JLabel();
        cb_danificado = new javax.swing.JComboBox<>();
        btn_salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        lbl_emprestado = new javax.swing.JLabel();
        cb_emprestado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 500));

        lbl_titulo_livros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_titulo_livros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo_livros.setText("Livros");
        lbl_titulo_livros.setAlignmentX(0.5F);
        lbl_titulo_livros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_livro.setText("Livro:");

        lbl_autor.setText("Autor:");

        lbl_editora.setText("Editora:");

        lbl_publicacao.setText("Publicação:");

        lbl_endereco.setText("Endereço:");

        lbl_genero.setText("Genero:");

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "Infantil", "Romance", "Terror", "Poesia", "Fantasia", "Suspense", "Ficção científica", "Ficção literária" }));
        cb_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_generoActionPerformed(evt);
            }
        });

        lbl_id.setText("ID:");

        lbl_paginas.setText("Paginas:");

        lbl_classificacao.setText("Classificação:");

        cb_classificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "12 Anos", "14 Anos", "16 Anos", "18 +" }));

        lbl_danificado.setText("Danificado:");

        cb_danificado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");

        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lbl_emprestado.setText("Emprestado");

        cb_emprestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(lbl_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(lbl_paginas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txt_qtdPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(393, 393, 393))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_publicacao)
                                    .addComponent(lbl_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_editora)
                                    .addComponent(lbl_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_endereco))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_endereco_Livros, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_editora)
                                        .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_publicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(btn_salvar)
                                .addGap(180, 180, 180)
                                .addComponent(btn_buscar)
                                .addGap(53, 53, 53)
                                .addComponent(btn_excluir)
                                .addGap(64, 64, 64)
                                .addComponent(btn_sair)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_editar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_danificado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(cb_danificado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(lbl_emprestado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_emprestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_titulo_livros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_titulo_livros, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_genero)
                    .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_paginas)
                    .addComponent(txt_qtdPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_autor))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_editora))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_publicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_publicacao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_endereco_Livros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_endereco)))
                    .addComponent(lbl_livro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_emprestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_classificacao)
                        .addComponent(cb_classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_danificado)
                        .addComponent(cb_danificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_emprestado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluir)
                    .addComponent(btn_editar)
                    .addComponent(btn_salvar)
                    .addComponent(btn_sair)
                    .addComponent(btn_buscar))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_generoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        inserir_livros();
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        
        frm_menu objfrm_menu = new frm_menu();
                objfrm_menu.setVisible(true);
                
                dispose();
                
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        
        Alterar_livro();
        
        
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        
        buscar_item();
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_livros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_livros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cb_classificacao;
    private javax.swing.JComboBox<String> cb_danificado;
    private javax.swing.JComboBox<String> cb_emprestado;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_classificacao;
    private javax.swing.JLabel lbl_danificado;
    private javax.swing.JLabel lbl_editora;
    private javax.swing.JLabel lbl_emprestado;
    private javax.swing.JLabel lbl_endereco;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_livro;
    private javax.swing.JLabel lbl_paginas;
    private javax.swing.JLabel lbl_publicacao;
    private javax.swing.JLabel lbl_titulo_livros;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_editora;
    private javax.swing.JTextField txt_endereco_Livros;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_livro;
    private javax.swing.JTextField txt_publicacao;
    private javax.swing.JTextField txt_qtdPaginas;
    // End of variables declaration//GEN-END:variables



 private int inserir_livros(){
       
       String livro, autor, editora, publicacao, endereco, genero, paginas, classificacao, danificado, emprestado;
       
       
       livro = txt_livro.getText();
       autor = txt_autor.getText();
       editora = txt_editora.getText();
       publicacao = txt_publicacao.getText();
       endereco = txt_endereco_Livros.getText();
       genero = (String) cb_genero.getSelectedItem();
       paginas = txt_qtdPaginas.getText();
       classificacao = (String) cb_classificacao.getSelectedItem();
       danificado = (String) cb_danificado.getSelectedItem();
       emprestado = (String) cb_emprestado.getSelectedItem();
       
       Livros objlivros = new Livros();
       objlivros.setNome(livro);
       objlivros.setAutor(autor);
       objlivros.setEditora(editora);
       objlivros.setPublicacao(publicacao);
       objlivros.setEndereco(endereco);
       objlivros.setGereno(genero);
       objlivros.setPaginas(paginas);
       objlivros.setClassificacao(classificacao);
       objlivros.setDanificado(danificado);
       objlivros.setEmprestado(emprestado);
       
       livros_DAO objlivros_dao = new livros_DAO();
       objlivros_dao.cadastrar_livros(objlivros);
       return 0;
   }
 
 

    private void Alterar_livro(){
            int id_livro;
            String nome_livro, autor, editora, publicacao, genero, paginas, classificacao, danificado, endereco, emprestado;
            
         id_livro = Integer.parseInt(txt_id.getText());
         nome_livro = txt_livro.getText();
         endereco = txt_endereco_Livros.getText();
         autor = txt_autor.getText();
         editora = txt_editora.getText();
         publicacao = txt_publicacao.getText();
         genero = (String) cb_genero.getSelectedItem();
         paginas = txt_qtdPaginas.getText();
         classificacao = (String) cb_classificacao.getSelectedItem();
         danificado = (String) cb_danificado.getSelectedItem();
         emprestado = (String) cb_emprestado.getSelectedItem();
         
         Livros objlivros = new Livros();
         
         objlivros.setId(id_livro);
         objlivros.setNome(nome_livro);
         objlivros.setAutor(autor);
         objlivros.setEditora(editora);
         objlivros.setPublicacao(publicacao);
         objlivros.setGereno(genero);
         objlivros.setPaginas(paginas);
         objlivros.setClassificacao(classificacao);
         objlivros.setDanificado(danificado);
         objlivros.setEndereco(endereco);
         objlivros.setEmprestado(emprestado);
         
         livros_DAO objlivros_dao = new livros_DAO();
         objlivros_dao.alterar_livros(objlivros);
         
        }
    
    private void buscar_item(){
    
    String sql = " select * from livros where id = " + txt_id.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                txt_id.setText("" + rs.getInt("id"));
                txt_livro.setText("" + rs.getString("nome"));
                txt_autor.setText("" + rs.getString("autor"));
                txt_editora.setText("" + rs.getString("editora"));
                txt_publicacao.setText("" + rs.getString("publicacao"));
                cb_genero.setSelectedItem("" + rs.getString("genero"));
                txt_qtdPaginas.setText("" + rs.getString("paginas"));
                cb_classificacao.setSelectedItem("" + rs.getString("classificacao"));
                cb_danificado.setSelectedItem("" + rs.getString("danificado"));
                txt_endereco_Livros.setText("" + rs.getString("endereco"));
                cb_emprestado.setSelectedItem("" + rs.getString("emprestado"));

            }
        }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }

       

    }
 

}
