/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;

import DAO.conexao_DAO;
import DAO.funcionarios_DAO;
import DAO.livros_DAO;
import conexao.Funcionarios;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author will
 */
public class frm_funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form frm_funcionarios
     */
    public frm_funcionarios() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JButton();
        lbl_cpf = new javax.swing.JLabel();
        lbl_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        txt_cpf_funcionarios = new javax.swing.JTextField();
        lbl_nome_funcionarios = new javax.swing.JLabel();
        txt_nome_funcionarios = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_senha_funcionarios = new javax.swing.JTextField();
        lbl_final = new javax.swing.JLabel();
        btn_buscar_funcionarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_sair.setText("Sair");
        btn_sair.setActionCommand("");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE FUNCIONARIOS");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        lbl_cpf.setText("CPF: ");

        lbl_editar.setText("Editar");
        lbl_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_editarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");

        lbl_nome_funcionarios.setText("Nome:");

        lbl_senha.setText("Senha:");

        lbl_final.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_buscar_funcionarios.setText("Buscar");
        btn_buscar_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_funcionariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btn_cadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar_funcionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_excluir)
                .addGap(18, 18, 18)
                .addComponent(btn_sair)
                .addGap(26, 26, 26))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_senha_funcionarios))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nome_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nome_funcionarios))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cpf_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbl_final, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cpf)
                    .addComponent(txt_cpf_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome_funcionarios)
                    .addComponent(txt_nome_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_senha)
                    .addComponent(txt_senha_funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lbl_final, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sair)
                    .addComponent(btn_cadastrar)
                    .addComponent(lbl_editar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_buscar_funcionarios))
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        
        frm_menu objfrm_menu = new frm_menu();
                objfrm_menu.setVisible(true);
                
                dispose();
                
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        // TODO add your handling code here:
        inserir_funcionarios();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_buscar_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_funcionariosActionPerformed
        // TODO add your handling code here:
        
        buscar_funcionarios();
    }//GEN-LAST:event_btn_buscar_funcionariosActionPerformed

    private void lbl_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_editarActionPerformed
        // TODO add your handling code here:
        
        Alterar_funcionario();
    }//GEN-LAST:event_lbl_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_funcionarios;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JButton lbl_editar;
    private javax.swing.JLabel lbl_final;
    private javax.swing.JLabel lbl_nome_funcionarios;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JTextField txt_cpf_funcionarios;
    private javax.swing.JTextField txt_nome_funcionarios;
    private javax.swing.JTextField txt_senha_funcionarios;
    // End of variables declaration//GEN-END:variables


   private int inserir_funcionarios(){
       
       String cpf, nome, senha;
       
       cpf = txt_cpf_funcionarios.getText();
       nome = txt_nome_funcionarios.getText();
       senha = txt_senha_funcionarios.getText();
       
       Funcionarios objfuncionarios = new Funcionarios();
       objfuncionarios.setCpf(cpf);
       objfuncionarios.setNome(nome);
       objfuncionarios.setSenha(senha);
       funcionarios_DAO objfuncionarios_dao = new funcionarios_DAO();
       objfuncionarios_dao.cadastrar_funcionarios(objfuncionarios);
       return 0;
   }
   
   private void buscar_funcionarios(){
    
    String sql = " select * from funcionarios where cpf = " + txt_cpf_funcionarios.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                txt_cpf_funcionarios.setText("" + rs.getInt("cpf"));
                txt_nome_funcionarios.setText("" + rs.getString("nome"));
                txt_senha_funcionarios.setText("" + rs.getString("senha"));

            }
        }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }

       

    }
   
   
     private void Alterar_funcionario(){
           
            String cpf, nome,senha;
            
         cpf = txt_cpf_funcionarios.getText();
         nome = txt_nome_funcionarios.getText();
         senha = txt_senha_funcionarios.getText();
         
         
         Funcionarios objfuncionarios = new Funcionarios();
         
         objfuncionarios.setCpf(cpf);
         objfuncionarios.setNome(nome);
         objfuncionarios.setSenha(senha);
         
         funcionarios_DAO objfuncionarios_dao = new funcionarios_DAO();
         objfuncionarios_dao.alterar_funcionarios(objfuncionarios);
         
        }
}
       



