/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;

import DAO.funcionarios_DAO;
import DAO.livros_DAO;
import conexao.Funcionarios;
import conexao.Usuarios;
import DAO.usuarios_DAO;
import java.sql.ResultSet;

/**
 *
 * @author will
 */
public class frm_usuarios extends javax.swing.JFrame {

    /**
     * Creates new form frm_usuarios
     */
    public frm_usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        txt_cpf_usuarios = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        txt_nome_usuarios = new javax.swing.JTextField();
        lbl_nascimento = new javax.swing.JLabel();
        txt_nascimento_usuarios = new javax.swing.JTextField();
        lbl_telefone = new javax.swing.JLabel();
        txt_telefone_usuarios = new javax.swing.JTextField();
        lbl_mail = new javax.swing.JLabel();
        txt_mail_usuarios = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_senha_usuarios = new javax.swing.JPasswordField();
        btn_cad = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuarios");

        lbl_cpf.setText("CPF:");

        lbl_nome.setText("Nome:");

        lbl_nascimento.setText("Nascimento:");

        lbl_telefone.setText("Telefone:");

        lbl_mail.setText("E-Mail:");

        txt_mail_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mail_usuariosActionPerformed(evt);
            }
        });

        lbl_senha.setText("Senha:");

        btn_cad.setText("Cadastar");
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");

        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nome_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(txt_cpf_usuarios)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nascimento_usuarios)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btn_cad)
                        .addGap(28, 28, 28)
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btn_editar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_excluir)
                        .addGap(38, 38, 38)
                        .addComponent(btn_sair))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_telefone_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(txt_mail_usuarios)
                        .addComponent(txt_senha_usuarios))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cpf)
                    .addComponent(txt_cpf_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_telefone)
                    .addComponent(txt_telefone_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_nome)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nome_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_mail)
                        .addComponent(txt_mail_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nascimento)
                    .addComponent(txt_nascimento_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_senha)
                    .addComponent(txt_senha_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cad)
                    .addComponent(btn_editar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_sair)
                    .addComponent(btn_buscar))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        
        frm_menu objfrm_menu = new frm_menu();
                objfrm_menu.setVisible(true);
                
                dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
        // TODO add your handling code here:
        
        inserir_usuarios();
        
    }//GEN-LAST:event_btn_cadActionPerformed

    private void txt_mail_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mail_usuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mail_usuariosActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        
        buscar_usuarios();
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        
        Alterar_usuario();
    }//GEN-LAST:event_btn_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_nascimento;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTextField txt_cpf_usuarios;
    private javax.swing.JTextField txt_mail_usuarios;
    private javax.swing.JTextField txt_nascimento_usuarios;
    private javax.swing.JTextField txt_nome_usuarios;
    private javax.swing.JPasswordField txt_senha_usuarios;
    private javax.swing.JTextField txt_telefone_usuarios;
    // End of variables declaration//GEN-END:variables


    private int inserir_usuarios(){
       
       String cpf, nome, nascimento, telefone, email, senha;
       
      
       cpf = txt_cpf_usuarios.getText();
       nome = txt_nome_usuarios.getText();
       nascimento = txt_nascimento_usuarios.getText();
       telefone = txt_telefone_usuarios.getText();
       email = txt_mail_usuarios.getText();
       senha = txt_senha_usuarios.getText();
      
       
       Usuarios objusuarios = new Usuarios();
       objusuarios.setCpf(cpf);
       objusuarios.setNome(nome);
       objusuarios.setNascimento(nascimento);
       objusuarios.setTelefone(telefone);
       objusuarios.setEmail(email);
       objusuarios.setSenha(senha);
       usuarios_DAO objusuarios_dao = new usuarios_DAO();
       objusuarios_dao.cadastrar_usuarios(objusuarios);
       
       return 0;
   }
    
      private void buscar_usuarios(){
    
    String sql = " select * from usuarios where cpf = " + txt_cpf_usuarios.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                txt_cpf_usuarios.setText("" + rs.getInt("cpf"));
                txt_nome_usuarios.setText("" + rs.getString("nome"));
                txt_nascimento_usuarios.setText("" + rs.getString("nascimento"));
                txt_telefone_usuarios.setText("" + rs.getString("telefone"));
                txt_mail_usuarios.setText("" + rs.getString("email"));
                txt_senha_usuarios.setText("" + rs.getString("senha"));

            }
        }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }

       

    }
      
      
       private void Alterar_usuario(){
           
            String cpf, nome, nascimento,  telefone, email, senha;
            
         cpf = txt_cpf_usuarios.getText();
         nome = txt_nome_usuarios.getText();
         nascimento = txt_nascimento_usuarios.getText();
         telefone = txt_telefone_usuarios.getText();
         email = txt_mail_usuarios.getText();
         senha = txt_senha_usuarios.getText();
         
         
         Usuarios objusuarios = new Usuarios();
         
         objusuarios.setCpf(cpf);
         objusuarios.setNome(nome);
         objusuarios.setNascimento(nascimento);
         objusuarios.setTelefone(telefone);
         objusuarios.setEmail(email);
         objusuarios.setSenha(senha);
         
         usuarios_DAO objusuarios_dao = new usuarios_DAO();
         objusuarios_dao.alterar_usuarios(objusuarios);
         
        }
}
