/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bblioteca;

import DAO.livros_DAO;
import java.sql.ResultSet;
import DAO.conexao_DAO;
import DAO.funcionarios_DAO;
import DAO.livros_DAO;
import conexao.Funcionarios;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import DAO.emprestimo_DAO;
import DAO.usuarios_DAO;
import conexao.Emprestimo;
import conexao.Livros;
import conexao.Usuarios;
import java.util.ArrayList;

/**
 *
 * @author will
 */
public class frm_emprestimos extends javax.swing.JFrame {

    ResultSet rs;
    ArrayList<Emprestimo> listas = new ArrayList<>();
    Connection conn;
    PreparedStatement pstm;
    String sql;
    
    public frm_emprestimos() {
        initComponents();
       lbl_hora_atual.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date(System.currentTimeMillis())));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sair = new javax.swing.JButton();
        lbl_funcionario = new javax.swing.JLabel();
        txt_funcionario = new javax.swing.JTextField();
        lbl_emprestimos = new javax.swing.JLabel();
        lbl_id_livro = new javax.swing.JLabel();
        txt_id_livro = new javax.swing.JTextField();
        lbl_livro = new javax.swing.JLabel();
        txt_livro = new javax.swing.JTextField();
        lbl_emprestimo = new javax.swing.JLabel();
        txt_data_emprestimo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_data_devolucao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_emprestimos = new javax.swing.JTable();
        btn_inserir = new javax.swing.JButton();
        lbl_cpf_usuario = new javax.swing.JLabel();
        txt_cpf_usuario = new javax.swing.JTextField();
        lbl_noome_usuario = new javax.swing.JLabel();
        txt_nome_usuario = new javax.swing.JTextField();
        lbl_cpf_funcionario = new javax.swing.JLabel();
        txt_cpf_funcionario = new javax.swing.JTextField();
        lbl_senha_usuario = new javax.swing.JLabel();
        txt_senha_usuario = new javax.swing.JPasswordField();
        txt_data_devolvido = new javax.swing.JTextField();
        lbl_multa = new javax.swing.JLabel();
        txt_multa = new javax.swing.JTextField();
        lbl_hora_atual = new javax.swing.JLabel();
        lbl_id_livro_2 = new javax.swing.JLabel();
        txt_id_livro2 = new javax.swing.JTextField();
        lbl_livro_2 = new javax.swing.JLabel();
        txt_livro_2 = new javax.swing.JTextField();
        lbl_id_livro3 = new javax.swing.JLabel();
        txt_id_livro_3 = new javax.swing.JTextField();
        lbl_livro_3 = new javax.swing.JLabel();
        txt_livro_3 = new javax.swing.JTextField();
        btn_buscar_todos = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 550));

        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        lbl_funcionario.setText("Funcionario");

        txt_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_funcionarioActionPerformed(evt);
            }
        });

        lbl_emprestimos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_emprestimos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_emprestimos.setText("Efetuar emprestimo");
        lbl_emprestimos.setToolTipText("");

        lbl_id_livro.setText("ID livro");

        txt_id_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_livroActionPerformed(evt);
            }
        });

        lbl_livro.setText("Livro");

        lbl_emprestimo.setText("Emprestimo");

        jLabel1.setText("Devolução");

        jLabel2.setText("Devolvido");

        tb_emprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Funcionario", "CPF cliente", "Nome cliente", "ID livro", "Livro", "ID livro 2", "Livro 2", "ID livro 3", "Livro 3", "Data emprestimo", "Data devolução", "Devolvido?", "Multa"
            }
        ));
        jScrollPane1.setViewportView(tb_emprestimos);

        btn_inserir.setText("Inserir");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        lbl_cpf_usuario.setText("CPF usuario");

        txt_cpf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf_usuarioActionPerformed(evt);
            }
        });

        lbl_noome_usuario.setText("Usuario");

        lbl_cpf_funcionario.setText("CPF Funcionario");

        txt_cpf_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpf_funcionarioActionPerformed(evt);
            }
        });

        lbl_senha_usuario.setText("Senha");

        txt_senha_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senha_usuarioActionPerformed(evt);
            }
        });

        lbl_multa.setText("Multa");

        lbl_id_livro_2.setText("ID livro 2");

        txt_id_livro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_livro2ActionPerformed(evt);
            }
        });

        lbl_livro_2.setText("Livro 2");

        lbl_id_livro3.setText("ID livro 3");

        txt_id_livro_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_livro_3ActionPerformed(evt);
            }
        });

        lbl_livro_3.setText("Livro 3");

        btn_buscar_todos.setText("Buscar todos");
        btn_buscar_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_todosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_emprestimos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_funcionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cpf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cpf_funcionario)
                            .addComponent(lbl_noome_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_nome_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addComponent(txt_cpf_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cpf_funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_livro_2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_livro_3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_senha_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_inserir)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_buscar_todos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(btn_sair))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_senha_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_data_devolvido, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_multa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(71, 71, 71)
                                            .addComponent(txt_multa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lbl_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_data_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(txt_data_devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lbl_id_livro3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbl_id_livro_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(55, 55, 55)
                                            .addComponent(txt_id_livro_3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbl_livro_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_id_livro2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbl_livro_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txt_id_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbl_livro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(lbl_hora_atual, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbl_emprestimos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_hora_atual, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cpf_funcionario)
                            .addComponent(txt_cpf_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_funcionario)
                            .addComponent(txt_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cpf_usuario)
                            .addComponent(txt_cpf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_noome_usuario)
                            .addComponent(txt_nome_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id_livro)
                            .addComponent(txt_id_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_livro)
                            .addComponent(txt_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id_livro_2)
                            .addComponent(txt_id_livro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_livro_2)
                            .addComponent(txt_livro_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id_livro_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_id_livro3)
                            .addComponent(lbl_livro_3)
                            .addComponent(txt_livro_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_data_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_emprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txt_data_devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_data_devolvido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(lbl_senha_usuario))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_multa)
                                    .addComponent(txt_multa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addComponent(txt_senha_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_inserir)
                                    .addComponent(btn_sair)
                                    .addComponent(btn_buscar_todos))))
                        .addGap(57, 57, 57))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        
        frm_menu objfrm_menu = new frm_menu();
                objfrm_menu.setVisible(true);
                
                dispose();
                
    }//GEN-LAST:event_btn_sairActionPerformed

    private void txt_id_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_livroActionPerformed
        // TODO add your handling code here:
        
        buscar_item();
    }//GEN-LAST:event_txt_id_livroActionPerformed

    private void txt_cpf_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf_funcionarioActionPerformed
        // TODO add your handling code here:
        
        buscar_funcionarios();
        
         
   
    }//GEN-LAST:event_txt_cpf_funcionarioActionPerformed

    private void txt_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_funcionarioActionPerformed

    private void txt_cpf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpf_usuarioActionPerformed
        // TODO add your handling code here:
        
         buscar_usuarios();
    }//GEN-LAST:event_txt_cpf_usuarioActionPerformed

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
        // TODO add your handling code here:
        
        Logar();
        
    }//GEN-LAST:event_btn_inserirActionPerformed

    private void txt_id_livro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_livro2ActionPerformed
        // TODO add your handling code here:
        
        buscar_livro2();
    }//GEN-LAST:event_txt_id_livro2ActionPerformed

    private void txt_id_livro_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_livro_3ActionPerformed
        // TODO add your handling code here:
        buscar_livro3();
    }//GEN-LAST:event_txt_id_livro_3ActionPerformed

    private void txt_senha_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senha_usuarioActionPerformed
        // TODO add your handling code here:
        
         Logar();
    }//GEN-LAST:event_txt_senha_usuarioActionPerformed

    private void btn_buscar_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_todosActionPerformed
        // TODO add your handling code here:
        
        listar_emprestimo();
        
        
        
    }//GEN-LAST:event_btn_buscar_todosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_emprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_emprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_emprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_emprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_emprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_buscar_todos;
    private javax.swing.JButton btn_inserir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cpf_funcionario;
    private javax.swing.JLabel lbl_cpf_usuario;
    private javax.swing.JLabel lbl_emprestimo;
    private javax.swing.JLabel lbl_emprestimos;
    private javax.swing.JLabel lbl_funcionario;
    private javax.swing.JLabel lbl_hora_atual;
    private javax.swing.JLabel lbl_id_livro;
    private javax.swing.JLabel lbl_id_livro3;
    private javax.swing.JLabel lbl_id_livro_2;
    private javax.swing.JLabel lbl_livro;
    private javax.swing.JLabel lbl_livro_2;
    private javax.swing.JLabel lbl_livro_3;
    private javax.swing.JLabel lbl_multa;
    private javax.swing.JLabel lbl_noome_usuario;
    private javax.swing.JLabel lbl_senha_usuario;
    private javax.swing.JTable tb_emprestimos;
    private javax.swing.JTextField txt_cpf_funcionario;
    private javax.swing.JTextField txt_cpf_usuario;
    private javax.swing.JTextField txt_data_devolucao;
    private javax.swing.JTextField txt_data_devolvido;
    private javax.swing.JTextField txt_data_emprestimo;
    private javax.swing.JTextField txt_funcionario;
    private javax.swing.JTextField txt_id_livro;
    private javax.swing.JTextField txt_id_livro2;
    private javax.swing.JTextField txt_id_livro_3;
    private javax.swing.JTextField txt_livro;
    private javax.swing.JTextField txt_livro_2;
    private javax.swing.JTextField txt_livro_3;
    private javax.swing.JTextField txt_multa;
    private javax.swing.JTextField txt_nome_usuario;
    private javax.swing.JPasswordField txt_senha_usuario;
    // End of variables declaration//GEN-END:variables


  private void buscar_funcionarios(){
    
    String sql = " select * from funcionarios where cpf = " + txt_cpf_funcionario.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                
                txt_funcionario.setText("" + rs.getString("nome"));

            }
        }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }
       
    }
  
  
  private void buscar_usuarios(){
    
    String sql = " select * from usuarios where cpf = " + txt_cpf_usuario.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                
                txt_nome_usuario.setText("" + rs.getString("nome"));
                

            } }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }
  }
  
  private void buscar_item(){
    
    String sql = " select * from livros where id = " + txt_id_livro.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                
                txt_livro.setText("" + rs.getString("nome"));
                

            }
        }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }
  }

   private void buscar_livro2(){
    
    String sql = " select * from livros where id = " + txt_id_livro2.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                
                txt_livro_2.setText("" + rs.getString("nome"));
                

            }
        }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }
  }
   
    private void buscar_livro3(){
    
    String sql = " select * from livros where id = " + txt_id_livro_3.getText();
        try
        {
            livros_DAO objlivros_dao = new livros_DAO();
            ResultSet rs = objlivros_dao.executarconsulta(sql);
            while (rs.next())
            {
                
                txt_livro_3.setText("" + rs.getString("nome"));
                

            }
        }
        catch (Exception erro)
        {
            System.out.println("Problema na busca");
        }
  }
  
  
  public class TesteDatas {
  public static void main(String args[]) {
      SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
      Date dataBase = null;
      Date vencimento = null;
      try {
         dataBase = sdf.parse("07/10/1997");
         vencimento = sdf.parse("03/07/2000");
      } catch (java.text.ParseException e) { return; }

      long diferencaMS = vencimento.getTime() - dataBase.getTime();
      long diferencaSegundos = diferencaMS / 1000;
      long diferencaMinutos = diferencaSegundos / 60;
      long diferencaHoras = diferencaMinutos / 60;
      long diferencaDias = diferencaHoras / 24;

      System.out.println(diferencaMS);
      System.out.println(diferencaSegundos);
      System.out.println(diferencaMinutos);
      System.out.println(diferencaHoras);
      System.out.println(diferencaDias);
   
  }
}
  
  private int fazer_emprestimos(){
       
       String cpf_funcionario, funcionario, cpf_usuario, usuario, nome_livro, nome_livro_2, nome_livro_3, data_emprestimo, data_devolucao, data_devolvido;
       int id_livro,id_livro_2,id_livro_3;
       double multa;

       
       cpf_funcionario = txt_cpf_funcionario.getText();
       funcionario = txt_funcionario.getText();
       cpf_usuario = txt_cpf_usuario.getText();
       usuario = txt_nome_usuario.getText();
       id_livro = Integer.parseInt(txt_id_livro.getText());
       nome_livro = txt_livro.getText();
       id_livro_2 = Integer.parseInt(txt_id_livro2.getText()) ;
       nome_livro_2 = txt_livro_2.getText();
       id_livro_3 = Integer.parseInt(txt_id_livro_3.getText()) ;
       nome_livro_3 = txt_livro_3.getText();
       data_emprestimo = lbl_hora_atual.getText();
       data_devolucao = txt_data_devolucao.getText();
       data_devolvido = txt_data_devolvido.getText();
       multa = Double.parseDouble(txt_multa.getText());
        
       
       
       Emprestimo objemprestimo = new Emprestimo();
       objemprestimo.setCpfFuncionario(cpf_funcionario);
       objemprestimo.setFuncionario(funcionario);
       objemprestimo.setCpfUsuario(cpf_usuario);
       objemprestimo.setUsuario(usuario);
       objemprestimo.setIdLivro(id_livro);
       objemprestimo.setNomeLivro(nome_livro);
       objemprestimo.setIdLivro2(id_livro_2);
       objemprestimo.setNomeLivro2(nome_livro_2);
       objemprestimo.setIdLivro3(id_livro_3);
       objemprestimo.setNomeLivro3(nome_livro_3);
       objemprestimo.setDataEmprestimo(data_emprestimo);
       objemprestimo.setDataDevolucao(data_devolucao);
       objemprestimo.setDataDevolvido(data_devolvido);
       objemprestimo.setMulta(multa);
       
       emprestimo_DAO objemprestimo_dao = new emprestimo_DAO();
       objemprestimo_dao.fazer_emprestimo(objemprestimo);
       return 0;
   }

  private void Logar(){
 try {
            String cpf_usuario, senha_usuario;

            cpf_usuario = txt_cpf_usuario.getText();
            senha_usuario = txt_senha_usuario.getText();

            Usuarios objusuarios = new Usuarios();
            objusuarios.setCpf(cpf_usuario);
            objusuarios.setSenha(senha_usuario);
            
            usuarios_DAO objusuarios_dao = new usuarios_DAO();
            ResultSet rs_usuarios_dao = objusuarios_dao.logar_usuarios(objusuarios);
        
            if(rs_usuarios_dao.next()){
                //chamar tela
                
                fazer_emprestimos();
                listar_emprestimos();

                
            }else{
                //mensagem de erro
                JOptionPane.showMessageDialog(null, "Usuario ou senha invalida");
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null,"frm_emprestimo"+ erro);
        }
            
 


}
  

  private void listar_emprestimo() {
        try {
            sql = "select * from emprestimo where cpf_usuario = "+ txt_cpf_usuario;
            emprestimo_DAO objemprestimoDAO = new emprestimo_DAO();
            DefaultTableModel model = (DefaultTableModel) tb_emprestimos.getModel();
            model.setNumRows(0);
            ArrayList<Emprestimo> lista = objemprestimoDAO.pesquisar_emprestimo();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getCodigo(),
                    lista.get(num).getFuncionario(),
                    lista.get(num).getCpfUsuario(),
                    lista.get(num).getUsuario(),
                    lista.get(num).getIdLivro(),
                    lista.get(num).getNomeLivro(),
                    lista.get(num).getIdLivro2(),
                    lista.get(num).getNomeLivro2(),
                    lista.get(num).getIdLivro3(),
                    lista.get(num).getNomeLivro3(),
                    lista.get(num).getDataEmprestimo(),
                    lista.get(num).getDataDevolucao(),
                    lista.get(num).getDataDevolvido(),
                    lista.get(num).getMulta()

                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar_emprestimo" + erro);
        }
    }

  
    public ArrayList<Emprestimo> pesquisar_emprestimo() 
    {

        String sql = "select * from emprestimo where cpf_usuario = "+ txt_cpf_usuario;
        conn = new conexao_DAO().conectaBD();
        try {
            pstm = conn.prepareStatement(sql);
            rs = pstm.executeQuery();

            while (rs.next()) {
                Emprestimo objemprestimo = new Emprestimo();
                objemprestimo.setCodigo(rs.getInt("codigo"));
                objemprestimo.setCpfFuncionario(rs.getString("cpf_funcionario"));
                objemprestimo.setFuncionario(rs.getString("funcionario"));
                objemprestimo.setCpfUsuario(rs.getString("cpf_usuario"));
                objemprestimo.setUsuario(rs.getString("usuario"));
                objemprestimo.setIdLivro(rs.getInt("id_livro"));
                objemprestimo.setNomeLivro(rs.getString("nome_livro"));
                objemprestimo.setIdLivro2(rs.getInt("id_livro_2"));
                objemprestimo.setNomeLivro2(rs.getString("nome_livro_2"));
                objemprestimo.setIdLivro3(rs.getInt("id_livro_3"));
                objemprestimo.setNomeLivro3(rs.getString("nome_livro_3"));
                objemprestimo.setDataEmprestimo(rs.getString("data_emprestimo"));
                objemprestimo.setDataDevolucao(rs.getString("data_devolucao"));
                objemprestimo.setDataDevolvido(rs.getString("data_devolvido"));
                objemprestimo.setMulta(rs.getDouble("multa"));

                listas.add(objemprestimo);
            }

        } catch (SQLException erro) {

            JOptionPane.showMessageDialog(null, "frmemprestimo pesquisar_emprestimo: " + erro);
        }
        return listas;
    }
    
    private void listar_emprestimos() {
        try {
            
            DefaultTableModel model = (DefaultTableModel) tb_emprestimos.getModel();
            model.setNumRows(0);
            
            ArrayList<Emprestimo> lista = pesquisar_emprestimos();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getCodigo(),
                    lista.get(num).getCpfFuncionario(),
                    lista.get(num).getCpfUsuario(),
                    lista.get(num).getUsuario(),
                    lista.get(num).getIdLivro(),
                    lista.get(num).getNomeLivro(),
                    lista.get(num).getIdLivro2(),
                    lista.get(num).getNomeLivro2(),
                    lista.get(num).getIdLivro3(),
                    lista.get(num).getNomeLivro3(),
                    lista.get(num).getDataEmprestimo(),
                    lista.get(num).getDataDevolucao(),
                    lista.get(num).getDataDevolvido(),
                    lista.get(num).getMulta()

                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar_emprestimo" + erro);
        }
    }
    
    
    
    public ArrayList<Emprestimo> pesquisar_emprestimos() {

        sql = "select * from emprestimo where cpf_usuario = "+ txt_cpf_usuario.getText();
        conn = new conexao_DAO().conectaBD();
        try {
            pstm = conn.prepareStatement(sql);
            rs = pstm.executeQuery();

            while (rs.next()) {
                Emprestimo objemprestimo = new Emprestimo();
                objemprestimo.setCodigo(rs.getInt("codigo"));
                objemprestimo.setCpfFuncionario(rs.getString("cpf_funcionario"));
                objemprestimo.setFuncionario(rs.getString("funcionario"));
                objemprestimo.setCpfUsuario(rs.getString("cpf_usuario"));
                objemprestimo.setUsuario(rs.getString("usuario"));
                objemprestimo.setIdLivro(rs.getInt("id_livro"));
                objemprestimo.setNomeLivro(rs.getString("nome_livro"));
                objemprestimo.setIdLivro2(rs.getInt("id_livro_2"));
                objemprestimo.setNomeLivro2(rs.getString("nome_livro_2"));
                objemprestimo.setIdLivro3(rs.getInt("id_livro_3"));
                objemprestimo.setNomeLivro3(rs.getString("nome_livro_3"));
                objemprestimo.setDataEmprestimo(rs.getString("data_emprestimo"));
                objemprestimo.setDataDevolucao(rs.getString("data_devolucao"));
                objemprestimo.setDataDevolvido(rs.getString("data_devolvido"));
                objemprestimo.setMulta(rs.getDouble("multa"));

                listas.add(objemprestimo);
            }

        } catch (SQLException erro) {

            JOptionPane.showMessageDialog(null, "frm_emprestimo pesquisar_emprestimos: " + erro);
        }
        return listas;
    }
}
